# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20160131_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('picture', models.ImageField(upload_to='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='Food')),
                ('details', models.TextField()),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('picture', models.ImageField(upload_to='SubCategory')),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.CategoryName')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
        migrations.AddField(
            model_name='itemname',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.SubCategoryName'),
        ),
    ]
