# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20160229_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryname',
            name='picture',
            field=models.ImageField(blank=True, upload_to='Category'),
        ),
        migrations.AlterField(
            model_name='itemname',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subcategoryname',
            name='picture',
            field=models.ImageField(blank=True, upload_to='SubCategory'),
        ),
    ]
