# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20160229_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemname',
            old_name='picture',
            new_name='pic',
        ),
        migrations.AlterField(
            model_name='subcategoryname',
            name='categoryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='restaurant.CategoryName'),
        ),
    ]
